Maxplasse/foodclass

app/controllers/comments_controller.rb
app/controllers/courses_controller.rb
app/controllers/participants_controller.rb
app/controllers/posts_controller.rb
app/controllers/profiles_controller.rb
app/views/comments/create.html.erb
app/views/courses/index.html.erb
app/views/courses/show.html.erb
app/views/participants/past_participations.html.erb
app/views/participants/upcoming_participations.html.erb
app/views/posts/index.html.erb
app/views/profiles/show.html.erb
config/routes.rb
test/controllers/comments_controller_test.rb
test/controllers/courses_controller_test.rb
test/controllers/participants_controller_test.rb
test/controllers/posts_controller_test.rb
test/controllers/profiles_controller_test.rb

controllers * 5

---

Gemfile.lock
app/controllers/participants_controller.rb
app/models/participant.rb
config/routes.rb

methods for "participants" + routes for everything

Backend methods

---

app/controllers/posts_controller.rb
app/controllers/profiles_controller.rb

back-end-controllers methods

---

app/controllers/profiles_controller.rb

profile method change

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/participants_controller.rb
app/policies/application_policy.rb
app/policies/course_policy.rb
app/policies/participant_policy.rb
test/policies/course_policy_test.rb
test/policies/participant_policy_test.rb

set up pundit

---

app/controllers/courses_controller.rb
app/controllers/pages_controller.rb
app/controllers/posts_controller.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb

root and design

---

.gitignore

Protect my secret data in .env file

setup seeds et env

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_fonts.scss
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

1ere version dispo reste mail et lien à faire

footer 1ere version

---

app/models/course.rb
app/models/participation.rb
app/models/user.rb
db/seeds.rb

seed participations

---

app/controllers/participations_controller.rb
db/seeds.rb

finish seed and correction participation controller

finish seed and correction participation controller

---

app/views/participations/favorites.html.erb
app/views/participations/past_participations.html.erb
app/views/participations/upcoming_participations.html.erb

profiles views awaiting for card

profiles views awaiting for card

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_dashboard_navigation.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/javascript/controllers/carousel_controller.js
app/views/profiles/show.html.erb
app/views/shared/_dashboard_navigation.html.erb
app/views/shared/_navbar.html.erb

navbar and onglet front

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_cards.scss
app/views/courses/index.html.erb
app/views/participations/favorites.html.erb
app/views/participations/past_participations.html.erb
app/views/participations/upcoming_participations.html.erb
db/seeds.rb

correction seed (duration et favorite : true/false) et front sur les cards

correction seed et front cards

---

app/assets/stylesheets/components/_banner.scss
app/views/shared/_navbar.html.erb

quick changes

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/shared/_navbar.html.erb

petites corrections navbar

---

app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/navbar_controller.js
app/javascript/controllers/title_controller.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

style homepage

---

app/assets/stylesheets/components/_card_community.scss
app/assets/stylesheets/components/_index.scss
app/views/shared/_navbar.html.erb

communauty

---

app/assets/stylesheets/components/_navbar.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/shared/_navbar.html.erb

navbar design

---

app/assets/stylesheets/components/_carousel.scss
app/javascript/controllers/carousel_controller.js
app/views/pages/home.html.erb

ajout autoplay sur carousel + dots

---

app/javascript/controllers/navbar_controller.js
app/views/shared/_navbar.html.erb

navbar différente sur la home vs autres pages

navbar différente sur la home vs autres pages

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_structure.scss
app/assets/stylesheets/pages/_home.scss
app/views/participations/favorites.html.erb
app/views/participations/past_participations.html.erb
app/views/participations/upcoming_participations.html.erb
app/views/profiles/show.html.erb
app/views/shared/_navbar.html.erb

homepage adjustments

---

app/assets/stylesheets/components/_hexagone.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/components/_progression_barre.scss
app/controllers/invitations_controller.rb
app/controllers/profiles_controller.rb
app/models/invitation.rb
app/models/user.rb
app/policies/invitation_policy.rb
app/views/profiles/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20220304101928_create_invitations.rb
db/schema.rb
test/controllers/invitations_controller_test.rb
test/models/invitation_test.rb

finish mon profil

---

app/assets/stylesheets/pages/_show.scss
app/views/courses/show.html.erb
app/views/profiles/show.html.erb

boutons pour commander avec modal

boutons pour commander avec modal

---

app/views/shared/_navbar.html.erb
db/schema.rb

ajout catégories du dashboard dans dropdown

ajout dans dropdown

---

app/assets/stylesheets/components/_card_community.scss
app/views/posts/index.html.erb
db/schema.rb
db/seeds.rb

adjustements on community page

adjustements on community page

---

db/seeds.rb

fixing bug

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

ok for navbar magnifique

---

app/controllers/participations_controller.rb
app/models/participation.rb
app/policies/participation_policy.rb
app/views/participations/past_participations.html.erb
config/routes.rb

fav/unfav sur les cours passés

fav/unfav sur les cours passés

---

app/controllers/courses_controller.rb
app/views/courses/show.html.erb

ajout du formulaire

---

app/views/courses/show.html.erb
app/views/posts/index.html.erb

solution provisoire

---

app/assets/stylesheets/components/_card.scss
app/controllers/participations_controller.rb
app/javascript/controllers/favorite_controller.js
app/views/participations/_card_course.html.erb
app/views/participations/past_participations.html.erb
config/routes.rb

front + js sur les fav / hover sur les cards

front + js sur les fav / hover sur les cards

---

app/assets/stylesheets/pages/_show.scss
app/views/courses/show.html.erb
app/views/layouts/application.html.erb

modifications des checkbox

---

app/views/courses/show.html.erb
app/views/posts/index.html.erb

heure mise en français

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/courses/_list.html.erb
app/views/courses/index.html.erb
app/views/participations/past_participations.html.erb

searchbar sticky et bouton réserver sur les courses

---

app/assets/stylesheets/pages/_show.scss
app/views/courses/show.html.erb

ajout bouton play sur la vidéo

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card_community.scss
app/controllers/emojis_controller.rb
app/models/emoji.rb
app/models/post.rb
app/models/user.rb
app/policies/emoji_policy.rb
app/views/courses/show.html.erb
app/views/posts/index.html.erb
config/routes.rb
db/migrate/20220308091131_create_emojis.rb
db/schema.rb
test/models/emoji_test.rb

cimmunity new design

---

app/assets/stylesheets/components/_box.scss
app/assets/stylesheets/components/_transition.scss
app/javascript/controllers/carousel_controller.js
app/javascript/controllers/transition_controller.js
app/views/layouts/application.html.erb
app/views/posts/index.html.erb
app/views/shared/_navbar.html.erb

transition wip

---

app/assets/stylesheets/components/_level_infos_boxes.scss
app/assets/stylesheets/components/_profile.scss
app/views/profiles/show.html.erb

ajustement profile page

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/title_controller.js
app/views/posts/index.html.erb

navbar cta

---

app/assets/stylesheets/components/_profile.scss
app/views/profiles/show.html.erb

form et padding

---

app/assets/stylesheets/components/_emoji.scss
app/assets/stylesheets/components/_index.scss
app/javascript/controllers/emojis_controller.js
app/models/emoji.rb
app/models/post.rb
app/views/posts/index.html.erb
db/seeds.rb

community emojis

---

app/views/courses/show.html.erb

add video chef

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card_community.scss
app/assets/stylesheets/components/_emoji.scss
app/assets/stylesheets/components/_navbar.scss
app/javascript/controllers/emojis_controller.js
app/views/posts/index.html.erb

wip community

---

app/assets/stylesheets/components/_dashboard_navigation.scss
app/assets/stylesheets/components/_level_infos_boxes.scss
app/assets/stylesheets/components/_profile.scss
app/views/profiles/show.html.erb

centrage bouton + modif des niveaux + onglets profils

---

app/assets/config/manifest.js
app/assets/stylesheets/pages/_show.scss
app/views/courses/show.html.erb
db/seeds.rb

petites modifs sur la show + seed des posts tajine

petites modifs sur la show + seed des posts tajine

---

app/assets/stylesheets/components/_level_infos_boxes.scss
app/assets/stylesheets/components/_profile.scss
app/controllers/invitations_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_sweetalert.js
app/views/courses/show.html.erb
app/views/profiles/show.html.erb
package.json
yarn.lock

add sweet alert

---

app/assets/config/manifest.js
app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/components/_profile.scss
app/javascript/controllers/carousel_profile_controller.js
app/views/profiles/show.html.erb

carousel profile

---

app/assets/stylesheets/components/_transition.scss
app/javascript/controllers/transition_controller.js
app/views/layouts/application.html.erb

carrot fall
